Node: diffusion_pipeline.connectome_stage.compute_matrice
Working directory: /home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/connectome_stage/compute_matrice

Node inputs:

additional_maps = ['/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/reconstruction/dipy_SHORE/shore_gfa.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/reconstruction/dipy_SHORE/shore_gfa.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/reconstruction/dipy_SHORE/shore_msd.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/reconstruction/dipy_SHORE/shore_rtop_signal.nii.gz']
atlas_info = {}
compute_curvature = False
output_types = ['gPickle']
parcellation_scheme = Lausanne2018
roi_graphmls = ['/home/localadmin/DATA/ds-sample/derivatives/cmp-v3.2.0/sub-01/ses-01/anat/sub-01_ses-01_atlas-L2018_res-scale1_dseg.graphml', '/home/localadmin/DATA/ds-sample/derivatives/cmp-v3.2.0/sub-01/ses-01/anat/sub-01_ses-01_atlas-L2018_res-scale2_dseg.graphml', '/home/localadmin/DATA/ds-sample/derivatives/cmp-v3.2.0/sub-01/ses-01/anat/sub-01_ses-01_atlas-L2018_res-scale3_dseg.graphml', '/home/localadmin/DATA/ds-sample/derivatives/cmp-v3.2.0/sub-01/ses-01/anat/sub-01_ses-01_atlas-L2018_res-scale4_dseg.graphml', '/home/localadmin/DATA/ds-sample/derivatives/cmp-v3.2.0/sub-01/ses-01/anat/sub-01_ses-01_atlas-L2018_res-scale5_dseg.graphml']
roi_volumes = ['/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/dilate_rois/mapflow/_dilate_rois0/sub-01_ses-01_atlas-L2018_res-scale2_dseg_out_warped_dil.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/dilate_rois/mapflow/_dilate_rois1/sub-01_ses-01_atlas-L2018_res-scale3_dseg_out_warped_dil.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/dilate_rois/mapflow/_dilate_rois2/sub-01_ses-01_atlas-L2018_res-scale5_dseg_out_warped_dil.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/dilate_rois/mapflow/_dilate_rois3/sub-01_ses-01_atlas-L2018_res-scale4_dseg_out_warped_dil.nii.gz', '/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/dilate_rois/mapflow/_dilate_rois4/sub-01_ses-01_atlas-L2018_res-scale1_dseg_out_warped_dil.nii.gz']
track_file = ['/home/localadmin/DATA/ds-sample/derivatives/nipype-1.8.6/sub-01/ses-01/diffusion_pipeline/diffusion_stage/tracking/trackvis/converted.trk']
voxel_connectivity = <undefined>

Traceback (most recent call last):
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node compute_matrice.

Traceback:
	Traceback (most recent call last):
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/connectomemapper-3.2.0-py3.11.egg/cmtklib/connectome.py", line 771, in _run_interface
	    cmat(
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/connectomemapper-3.2.0-py3.11.egg/cmtklib/connectome.py", line 327, in cmat
	    h = np.array(t, dtype=np.object)
	                          ^^^^^^^^^
	  File "/opt/anaconda3/envs/cmp_updPack/lib/python3.11/site-packages/numpy/__init__.py", line 397, in __getattr__
	    raise AttributeError(__former_attrs__[attr], name=None)
	AttributeError: module 'numpy' has no attribute 'object'.
	`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
	The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
	    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

